=== amunroe1/amunroe1/Shopping_WebApp_CSE598/Group43/Account/App_Data/Members.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	
	<!-- 
          CSE 598: Assignment 6
		               Member Passwords schema
           Author: Mark Adan
          version: 0.1
     last updated: 11/19/25 
	-->
	<xs:element name="Members">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="member" type="MemberType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Member Details -->
	<xs:complexType name="MemberType">
		<xs:sequence>
			<xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="pwd" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
    <xs:attribute name="level" type="LevelType" use="required"/>
	</xs:complexType>
	
  <!-- Access Level-->
  <xs:simpleType name="LevelType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="admin"/>
      <xs:enumeration value="customer"/>
    </xs:restriction>    
  </xs:simpleType>
                 
</xs:schema>

=== amunroe1/amunroe1/Shopping_WebApp_CSE598/Group43/Account/App_Data/Members.xml
<?xml version="1.0" encoding="UTF-8"?>
<Members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Members.xsd">
  <!-- 
		   CSE 598 : Assignment 6
		             Members and Passwords
		     author: Mark Adan
        version: 0.1
	 last updated: 11/19/25 
	-->
  <member level="admin">
    <email>TA</email>
    <pwd>Fvh778$</pwd>
  </member>
  <member level="customer">
    <email>madan12@asu.edu</email>
    <pwd>pdgdq457</pwd>
  </member>
  <member level="customer">
    <email>madan12@yahoo.com</email>
    <pwd>pdgdq457</pwd>
  </member>
  <member level="customer">
    <email>madan12@gmail.com</email>
    <pwd>sdvvzrug</pwd>
  </member>
  <member level="customer">
    <email>mmmmmmmadan12@asu.edu</email>
    <pwd>pdgdq457</pwd>
  </member>
  <member level="customer">
    <email>janedoe@yahoo.com</email>
    <pwd>mdqh456</pwd>
  </member>
  <member level="customer">
    <email>johnsmith@yahoo.com</email>
    <pwd>4557</pwd>
  </member>
  <member level="customer">
    <email>madanabc@asu.edu</email>
    <pwd>489:;</pwd>
  </member>
  <member level="customer">
    <email>janedoe@gmail.com</email>
    <pwd>
    </pwd>
  </member>
  <member level="customer">
    <email>janedoe@123.com</email>
    <pwd>
    </pwd>
  </member>
  <member level="customer">
    <email>madan126@asu.edu</email>
    <pwd>
    </pwd>
  </member>
  <member level="customer">
    <email>janedoe@unlv.edu</email>
    <pwd>456</pwd>
  </member>
  <member level="customer">
    <email>markadan@yahoo.com</email>
    <pwd>4567</pwd>
  </member>
  <member level="customer">
    <email>madan@gmail.com</email>
    <pwd>4567</pwd>
  </member>
</Members>
